<a href="https://colab.research.google.com/github/pfeilbr/pytorch-playground/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [6]:
torch.rand(2,2)

tensor([[0.1502, 0.5426],
        [0.0062, 0.0239]])

In [8]:
x = torch.empty(2,3)
x

tensor([[-2.4449e-15,  4.5709e-41, -2.4449e-15],
        [ 4.5709e-41,  4.4842e-44,  0.0000e+00]])

In [9]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])